INSERT INTO clientes (id, nombres, apellidos, email, create_at) VALUES (1, 'Albert', 'Wesker', 'alberweskerum@gmail.com', '2022-01-02');
INSERT INTO clientes (id, nombres, apellidos, email, create_at) VALUES (2, 'Leon', 'S. Kennedy', 'leonskennedy1998@gmail.com', '2022-01-02');
INSERT INTO clientes (id, nombres, apellidos, email, create_at) VALUES (3, 'Claire', 'Redfield', 'claireredfield243@gmail.com', '2022-01-02');
INSERT INTO clientes (id, nombres, apellidos, email, create_at) VALUES (4, 'Jill', 'Valentine', 'rpdjill8@gmail.com', '2022-01-02');
INSERT INTO clientes (id, nombres, apellidos, email, create_at) VALUES (5, 'Victor', 'Vickers', 'vickkers1997@gmail.com', '2022-01-02');
INSERT INTO clientes (id, nombres, apellidos, email, create_at) VALUES (6, 'Jamie', 'Burton', 'leonskennedy1998@gmail.com', '2022-01-02');
INSERT INTO clientes (id, nombres, apellidos, email, create_at) VALUES (7, 'Julia', 'Scotts', 'leonskennedy1998@gmail.com', '2022-01-02');
INSERT INTO clientes (id, nombres, apellidos, email, create_at) VALUES (8, 'Marie', 'Mccvew', 'leonskennedy1998@gmail.com', '2022-01-02');
INSERT INTO clientes (id, nombres, apellidos, email, create_at) VALUES (9, 'Leon', 'S. Kennedy', 'leonskennedy1998@gmail.com', '2022-01-02');
INSERT INTO clientes (id, nombres, apellidos, email, create_at) VALUES (10, 'Leon', 'S. Kennedy', 'leonskennedy1998@gmail.com', '2022-01-02');
INSERT INTO clientes (id, nombres, apellidos, email, create_at) VALUES (11, 'Leon', 'S. Kennedy', 'leonskennedy1998@gmail.com', '2022-01-02');
INSERT INTO clientes (id, nombres, apellidos, email, create_at) VALUES (12, 'Leon', 'S. Kennedy', 'leonskennedy1998@gmail.com', '2022-01-02');
INSERT INTO clientes (id, nombres, apellidos, email, create_at) VALUES (13, 'Leon', 'S. Kennedy', 'leonskennedy1998@gmail.com', '2022-01-02');
INSERT INTO clientes (id, nombres, apellidos, email, create_at) VALUES (14, 'Leon', 'S. Kennedy', 'leonskennedy1998@gmail.com', '2022-01-02');
INSERT INTO clientes (id, nombres, apellidos, email, create_at) VALUES (15, 'Leon', 'S. Kennedy', 'leonskennedy1998@gmail.com', '2022-01-02');
INSERT INTO clientes (id, nombres, apellidos, email, create_at) VALUES (16, 'Leon', 'S. Kennedy', 'leonskennedy1998@gmail.com', '2022-01-02');
INSERT INTO clientes (id, nombres, apellidos, email, create_at) VALUES (17, 'Leon', 'S. Kennedy', 'leonskennedy1998@gmail.com', '2022-01-02');
INSERT INTO clientes (id, nombres, apellidos, email, create_at) VALUES (18, 'Leon', 'S. Kennedy', 'leonskennedy1998@gmail.com', '2022-01-02');
INSERT INTO clientes (id, nombres, apellidos, email, create_at) VALUES (19, 'Leon', 'S. Kennedy', 'leonskennedy1998@gmail.com', '2022-01-02');
INSERT INTO clientes (id, nombres, apellidos, email, create_at) VALUES (20, 'Leon', 'S. Kennedy', 'leonskennedy1998@gmail.com', '2022-01-02');
